### ISSUE TITLE
Broken website links appearing for some users

### ISSUE THREAD

**Issue by GambuzX** [NIAEFEUP/Website-NIAEFEUP#198] opened 2020-09-08 12:49 UTC
On the members page, on some members' thumbnail there appears a "website" icon that, when clicked, takes the user from "https://ni.fe.up.pt/members" to "https://ni.fe.up.pt/<member email>". This page does not exist.

Unverified guess: it happens when a member has a public profile and has not specified a personal website

Example:
Clicking on the following button 
![image](https://user-images.githubusercontent.com/32744387/92478271-d4496b00-f1d9-11ea-9e23-c303c5872112.png)

Takes the user to
![image](https://user-images.githubusercontent.com/32744387/92478378-fe029200-f1d9-11ea-8c02-80a275e531ae.png)

**Comment by xRuiAlves** [comment] 2020-10-01 13:35
@GambuzX Hey :wave: 

I was not able to reproduce the behavior you discribed. I tried making my profile public and then removing my personal website, but that caused the symbol to disappear (expected "correct" behavior).

However, I was able to reproduce that behavior when I set by personal website to be my email. I think it is simply redirecting you to a relative url if the provided value isn't an absolute url (`e.g.` if I set it to be "www.fe.up.pt", I get redirected to "https://ni.fe.up.pt/www.fe.up.pt").

Thus, I have the feeling this is not a "problem" _per se_, it is simply working as a regular `href` :stuck_out_tongue:

**Comment by miguelpduarte** [comment] 2020-12-27 15:51
@GambuzX, I agree with what @xRuiAlves has said. It seems to me that this is working as intended. Maybe if the user include the `mailto:` part this will work with emails, as this is most likely injecting the value directly in an `<a>`'s `href`, as Rui said.

Thus, one could use `mailto:testing123@gmail.com` as their "website" instead of just `testing123@gmail.com`.

Closing given this is working as intended.

**Closed as completed by miguelpduarte** 2020-12-27 15:51 UTC
